server:
  port: 9000
  servlet:
    context-path: /orms/

project:
  version: "@project.parent.version@"
  artifactId: "@project.artifactId@"
  description: "@project.description@"

spring:
  application:
    name: orms
  profiles:
    active: "@profiles.active@"