server:
  port: 9000
  servlet:
    context-path: /orms/

project:
  version: "@project.parent.version@"
  artifactId: "@project.artifactId@"
  description: "@project.description@"

spring:
  application:
    name: orms
  profiles:
    active: "@profiles.active@"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9j5ve65316l79136o.mysql.rds.aliyuncs.com/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: demo_db
    password: ADMIN123admin
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update #自动更新
      show-sql: true  #日志中显示sql语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect